# Usar imagen oficial de Node.js basada en Debian (versión más actual)
FROM node:24-bullseye AS builder

# Crear directorio de trabajo
WORKDIR /app

COPY . /app

# Instalar dependencias
RUN npm ci

# Compilar el proyecto
RUN npm run build
RUN npm run sentry:sourcemaps

FROM node:24-slim

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    git \
    wget \
    apt-transport-https \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# Instalar PowerShell 7
RUN wget -q https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y powershell \
    && rm -rf /var/lib/apt/lists/*

# Instalar módulo de Exchange Online
RUN pwsh -Command "Install-Module -Name ExchangeOnlineManagement -Force -AllowClobber"

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/scripts /app/scripts
COPY --from=builder /app/dist /app/dist

# Mantener el contenedor en ejecución para trabajo manual
CMD ["node", "./dist/index.js"]
