# Stage 1: Build the application using a standard Node image
FROM node:24-bullseye AS build

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Clean npm cache
RUN npm cache clean --force

# Install necessary packages and dependencies
RUN npm ci
RUN npm run build

# Stage 2: Build a minimal distroless image
FROM node:24-alpine

# Copy the node_modules and built app from the build stage
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist

# Set the working directory
WORKDIR /app

# Define the entry point, since distroless doesn't have a shell, npm or npx
# all command directly pass to 'node' terminal
CMD ["node", "./dist/src/validation-worker-main.js"]
