# Stage 1: Build the application using a standard Node image
FROM node:24-bullseye AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm ci

# Copia el código fuente y construye la aplicación
COPY . .
RUN npm run build

# Stage 2: Runtime minimo
FROM node:24-alpine

# Copia node_modules y la aplicación construida desde la etapa de build
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist

# Establece el directorio de trabajo
WORKDIR /app

# Define el punto de entrada, ya que distroless no tiene shell, npm o npx
# todos los comandos se pasan directamente al terminal 'node'
CMD ["node", "./dist/src/validation-worker-main.js"]
